[theme]
primaryColor = "#4CAF50"
backgroundColor = "#F9F9F9"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#000000"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false

[global]
hideMenuItems = ["GitHub", "Report a bug"]
